### ISSUE TITLE
Plug player plugins in a server plugin + other kind of plugins

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/craftyjs#11]
It would be better to put the code (currently in index.js) to plug the player plugins in a server plugin (say players.js or something). It would also be interesting to emit a "newPlayer" (player) server event, to allow external player plugins.

An other interesting thing about plugins would be to make some other kind of plugins, for example npc plugins which would be put at entity creation and would handle the action of the npc (/mob).
These new kind of plugins would be plugged in server plugins.

When implementing NPC plugins, make sure that it makes more sense to create npc plugins vs just implementing the action and logic of npc in a server plugin directly (I guess it depends how much code would be needed for npc)

**Comment by nevercast** [comment]
Can we also consider the idea of namespacing all events, so we can eventbus in the future and have cluster? 

server.player.new

**Comment by rom1504** [comment]
player have events, server have events. What's the point of namespacing ?
