### ISSUE TITLE
should package.json main be index.js ?

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/craftyjs#13]
So people can also use craftyjs as a lib ?

**Comment by nevercast** [comment]
When you use a module, it uses the main as the import anyway, does it not? If you require craftjs it'll load app.js.

app.js however does not do a module.export.

**Comment by nevercast** [comment]
I would suggest that index.js exports all our types and factory functions, and app.js requires './index.js' or '.'

**Comment by rom1504** [comment]
yes that's what we do. Hence the issue.
