### ISSUE TITLE
Implement PVP

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/craftyjs#14]
Working on it...

EDIT: Scratch that, Fighting with someone works fine with no neck movement.

**Comment by rom1504** [comment]
Something like that : 
1. find the packet of attacking (look at mineflayer bot.attack maybe)
2. look for the update health packet
3. update the health in player.entity.health
4. put that in a pvp.js player plugin

**Comment by rom1504** [comment]
https://github.com/andrewrk/mineflayer/blob/45df58afbfc98ad981d4e873261347e2e6f079da/lib/plugins/entities.js#L400

We need to add a serv.entities (indexed by entity id)
1. create it in players.js (or a new entities.js ?)
2. fill it in addPlayer
3. remove the entity on logout

Then you can use serv.entities to know which entity was attacked

**Comment by mhsjlw** [comment]
@rom1504 serv.entities complete.

**Comment by mhsjlw** [comment]
Done
