### ISSUE TITLE
Sprinting and crouching

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/craftyjs#22]
Working on it...

**Comment by rom1504** [comment]
Receive http://wiki.vg/Protocol#Entity_Action from the player.
Send http://wiki.vg/Protocol#Entity_Metadata to everybody else
Here are entity metadata values http://wiki.vg/Entities#Entity_Metadata_Format

sprinting is 0x08

I think something like [{"type":"byte","value":0x08}]
