### ISSUE TITLE
Logging doesn't actually work

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/craftyjs#24]
I enable logging but no log is created

**Comment by rom1504** [comment]
Pretty sure that's because you didn't create a logs dir.
(but we should check for that relative directory potential problem)

**Comment by mhsjlw** [comment]
@rom1504 Not the problem. I created a log directory, and if a log directory doesn't exist... craftyjs should create one

**Comment by rom1504** [comment]
The main problem was it wasn't using the correct dir. Now it is, problem fixed.
